---
- src: DavidWittman.redis
  version: 1.2.5

- src: geerlingguy.certbot
  version: 3.0.2

- src: geerlingguy.composer
  version: 1.7.3

- src: geerlingguy.php
  version: 3.7.0

- src: geerlingguy.php-versions
  version: 3.0.0

- src: geerlingguy.mysql
  version: 2.9.4

- src: geerlingguy.nginx
  version: 2.6.2
